In [1]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5])

In [6]:
arr1.shape

(5,)

In [8]:
arr1 = np.array([1,2,3,4,5], dtype=np.float)

C:\Users\775D~1\AppData\Local\Temp/ipykernel_3912/1337087596.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([1,2,3,4,5], dtype=np.float)


In [9]:
arr1.dtype

dtype('float64')

In [10]:
range(10,20,2)

range(10, 20, 2)

In [13]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3 = np.arange(0,10,1.5)
arr3

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [16]:
arr_random = np.random.random((10,))

In [17]:
arr_random

array([0.58740066, 0.22491523, 0.55838758, 0.02121006, 0.55522948,
       0.38343906, 0.54661096, 0.21076007, 0.35130481, 0.16981436])

In [18]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#a = [1,2,3,4,5]
#b = [1**2 for in a]

In [21]:
arr2_sqrt=np.sqrt(arr2)

In [22]:
arr2_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [23]:
np.sin(arr2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [24]:
arr1 = np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
arr1+arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [26]:
arr1*arr2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [27]:
arr1**2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [28]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
arr1.max()

19

In [31]:
arr1.mean()

14.5

In [32]:
arr1.sum()

145

In [34]:
arr1.std()

2.8722813232690143

In [35]:
arr1 > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [39]:
arr4 = np.array([2,4,6,8,10])
arr4

array([ 2,  4,  6,  8, 10])

In [41]:
arr4.ndim

1

In [42]:
arr4.shape

(5,)

In [46]:
a = arr4.std()
a

2.8284271247461903

In [52]:
a_sqrt = np.sqrt(a)
a_sqrt

1.6817928305074292

In [53]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.insert(arr2, 5, 10)

array([ 0,  1,  2,  3,  4, 10,  5,  6,  7,  8,  9])

In [55]:
np.delete(arr2, 5)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [57]:
arr5 = np.array([1,10,5,33,3])
np.sort(arr5)

array([ 1,  3,  5, 10, 33])

In [58]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr = np.concatenate((arr1,arr2))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [62]:
arr[(arr < 5)]

array([0, 1, 2, 3, 4])

In [65]:
arr[(arr < 10) & (arr > 5)]

array([6, 7, 8, 9])

In [66]:
arr[(arr < 3) & (arr > 17)]

array([], dtype=int32)

In [67]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
matrix = np.array([(11,12,13),(1,2,3),(21,22,23)])
matrix

array([[11, 12, 13],
       [ 1,  2,  3],
       [21, 22, 23]])

In [70]:
matrix.shape

(3, 3)

In [71]:
matrix.ndim

2

In [73]:
matrix1.size

9

In [74]:
matrix1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [75]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [84]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.empty(2)

array([4.08632284e-89, 6.70824651e+01])

In [86]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a = np.empty_like(arr2)
a

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0, 1072693248,          0, 1072693248])

In [90]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [91]:
matrix1+matrix2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [97]:
np.delete(matrix1, 1, axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [98]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
np.mean(matrix1, axis=0)

array([4., 5., 6.])

In [102]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [103]:
matrix2[1,2]

15

In [104]:
matrix2[: , 1]

array([11, 14, 17])

In [105]:
matrix2[matrix2 > 10]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [106]:
matrix < 5

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [110]:
matrix3 = np.array([(1,4,7),(3,8,5),(9,2,6),(11,0,22)])
matrix3

array([[ 1,  4,  7],
       [ 3,  8,  5],
       [ 9,  2,  6],
       [11,  0, 22]])

In [111]:
matrix3.size

12

In [112]:
matrix4 = np.array([(67,4,23),(44,12,7),(88,6,0),(65,2,17)])
matrix4

array([[67,  4, 23],
       [44, 12,  7],
       [88,  6,  0],
       [65,  2, 17]])

In [122]:
np.append(matrix4,np.array([1,2,3]))

array([67,  4, 23, 44, 12,  7, 88,  6,  0, 65,  2, 17,  1,  2,  3])

In [123]:
matrix3[:,1]

array([4, 8, 2, 0])

In [124]:
matrix3[2,:]

array([9, 2, 6])

In [127]:
matrix4[matrix4 > 5]

array([67, 23, 44, 12,  7, 88,  6, 65, 17])